service: boof-scrapers

# Only deploy with a specific Serverless Framework version
frameworkVersion: =1.23.0

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::better-odds-data"
  stage: ${env:SERVERLESS_ENV}
  region: us-west-2 # Default is us-east-1
  timeout: 60 # Default is 6 seconds
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    DEF_VS_OBJECT_PATH: ${env:DEF_VS_OBJECT_PATH}
    CONSISTENCY_OBJECT_PATH: ${env:CONSISTENCY_OBJECT_PATH}
    CONSISTENCY_URL: ${env:CONSISTENCY_URL}
    SNAP_COUNT_OBJECT_PATH: ${env:SNAP_COUNT_OBJECT_PATH}
    PROJECTION_OBJECT_PATH: ${env:PROJECTION_OBJECT_PATH}
    PLAYER_STAT_OBJECT_PATH: ${env:PLAYER_STAT_OBJECT_PATH}
    SALARY_OBJECT_PATH: ${env:SALARY_OBJECT_PATH}
    FANT_DATA_EMAIL: ${env:FANT_DATA_EMAIL}
    FANT_DATA_PASSWORD: ${env:FANT_DATA_PASSWORD}
    CURRENT_WEEK: ${env:CURRENT_WEEK}

package:
  individually: true
  exclude:
    - .git/**
    - functions/**
    - resources/**
    - .DS_Store
    - .editorconfig
    - .env
    - .env.sample
    - .gitignore
    - aws.sh
    - package.json
    - README.md
    - requirements.txt
    - serverless.yml
  excludeDevDependencies: false

functions:
  def_vs_scraper:
    handler: functions/scrape/def_vs.scraper
    description: Scrape defense vs data
    package:
      include:
        - functions/scrape/def_vs.py
        - vendored/**
  fanduel_salaries_scraper:
    handler: functions/scrape/fanduel_salaries.scraper
    description: Scrape Fanduel salary data
    package:
      include:
        - functions/scrape/fanduel_salaries.py
        - vendored/**
  player_projections_scraper:
    handler: functions/scrape/player_projections.scraper
    description: Scrape player projection data
    package:
      include:
        - functions/scrape/player_projections.py
        - vendored/**
  player_stats_scraper:
    handler: functions/scrape/player_stats.scraper
    description: Scrape player stats data
    package:
      include:
        - functions/scrape/player_stats.py
        - vendored/**
  snap_counts_scraper:
    handler: functions/scrape/snap_counts.scraper
    description: Scrape player snap counts data
    package:
      include:
        - functions/scrape/snap_counts.py
        - vendored/**
  consistency_ratings_scraper:
    handler: functions/scrape/consistency_ratings.scraper
    description: Scrape player consistency data
    package:
      include:
        - functions/scrape/consistency_ratings.py
        - vendored/**
  insert_player_game_stats:
    handler: functions/insert/player_game_stats.main
    description: Insert player game stats
    package:
      include:
        - functions/insert/player_game_stats.py
        - vendored/**
