service: boof-scrapers

# Only deploy with a specific Serverless Framework version
frameworkVersion: =1.23.0

provider:
  name: aws
  runtime: python3.6
  stage: ${env:SERVERLESS_ENV}
  region: us-west-2 # Default is us-east-1
  timeout: 60 # Default is 6 seconds
  environment:
    MYSQL_HOST: ${env:MYSQL_HOST}
    MYSQL_PORT: ${env:MYSQL_PORT}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE}

package:
  individually: true
  exclude:
    - .git/**
    - functions/**
    - resources/**
    - .DS_Store
    - .editorconfig
    - .env
    - .env.sample
    - .gitignore
    - aws.sh
    - package.json
    - README.md
    - requirements.txt
    - serverless.yml
  excludeDevDependencies: false