service: boof-scrapers

# Only deploy with a specific Serverless Framework version
frameworkVersion: =1.23.0

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::better-odds-data"
  stage: ${env:SERVERLESS_ENV}
  region: us-west-2 # Default is us-east-1
  timeout: 60 # Default is 6 seconds
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    DEF_VS_OBJECT_PATH: ${env:DEF_VS_OBJECT_PATH}
    CONSISTENCY_OBJECT_PATH: ${env:CONSISTENCY_OBJECT_PATH}
    SNAP_COUNT_OBJECT_PATH: ${env:SNAP_COUNT_OBJECT_PATH}
    PROJECTION_OBJECT_PATH: ${env:PROJECTION_OBJECT_PATH}
    PLAYER_STAT_OBJECT_PATH: ${env:PLAYER_STAT_OBJECT_PATH}
    SALARY_OBJECT_PATH: ${env:SALARY_OBJECT_PATH}
    FANT_DATA_EMAIL: ${env:FANT_DATA_EMAIL}
    FANT_DATA_PASSWORD: ${env:FANT_DATA_PASSWORD}

package:
  individually: true
  exclude:
    - .git/**
    - functions/**
    - resources/**
    - .DS_Store
    - .editorconfig
    - .env
    - .env.sample
    - .gitignore
    - aws.sh
    - package.json
    - README.md
    - requirements.txt
    - serverless.yml
  excludeDevDependencies: false

functions:
  def_vs_scraper:
    handler: functions/def_vs.scraper
    description: Scrape defense vs data
    package:
      include:
        - functions/def_vs.py
        - vendored/**